apiVersion: common.contrail.com/v1alpha1
kind: Csrx
metadata:
  name: csrx-1
spec:
  initImage: docker.io/michaelhenkel/csrx-init:latest
  csrxImage: hub.juniper.net/security/csrx:18.1R1.9
  imagePullSecrets:
  - csrx
  networks:
    - name: net1
    - name: net2
