cat role.yaml > create-csrx-operator.yaml
echo "---" >> create-csrx-operator.yaml
cat service_account.yaml >> create-csrx-operator.yaml
echo "---" >> create-csrx-operator.yaml
cat role_binding.yaml >> create-csrx-operator.yaml
echo "---" >> create-csrx-operator.yaml
cat crds/common_v1alpha1_csrx_crd.yaml >> create-csrx-operator.yaml
echo "---" >> create-csrx-operator.yaml
cat operator.yaml >> create-csrx-operator.yaml
