apiVersion: apps/v1
kind: Deployment
metadata:
  name: csrx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csrx-operator
  template:
    metadata:
      labels:
        name: csrx-operator
    spec:
      serviceAccountName: csrx-operator
      containers:
        - name: csrx-operator
          # Replace this with the built image name
          image: docker.io/michaelhenkel/csrx-operator:latest
          command:
          - csrx-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csrx-operator"
